[project]
name = "blackjack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex Shrestha", email = "ashrest6@terpmail.umd.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "gh>=0.0.4",
    "gymnasium>=1.4.0",
]

[project.scripts]
blackjack = "blackjack:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
